// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD6HS5Hx9mVJrxgH0rbpQ2lU4cvCO_NGg',
    appId: '1:364633043807:web:fdf0fb9e70f1f298833cea',
    messagingSenderId: '364633043807',
    projectId: 'apiflet',
    authDomain: 'apiflet.firebaseapp.com',
    databaseURL: 'https://apiflet-default-rtdb.firebaseio.com',
    storageBucket: 'apiflet.appspot.com',
    measurementId: 'G-Y64HPLF58M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfZL-DpjHAFf4Tym8AEbkHl_BMABw3Z1g',
    appId: '1:364633043807:android:f4908a12157df6e3833cea',
    messagingSenderId: '364633043807',
    projectId: 'apiflet',
    databaseURL: 'https://apiflet-default-rtdb.firebaseio.com',
    storageBucket: 'apiflet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY57FWBiwHVFO8hyF_d86NP41wg2IpyKY',
    appId: '1:364633043807:ios:e8cfde3358d0b84f833cea',
    messagingSenderId: '364633043807',
    projectId: 'apiflet',
    databaseURL: 'https://apiflet-default-rtdb.firebaseio.com',
    storageBucket: 'apiflet.appspot.com',
    androidClientId: '364633043807-ao1j569621givu5mfksj843v9c4udjot.apps.googleusercontent.com',
    iosClientId: '364633043807-c0bptpv34g563u58fk5u2qci86h8ri7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.driversapp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY57FWBiwHVFO8hyF_d86NP41wg2IpyKY',
    appId: '1:364633043807:ios:d9dbdd2a32b266b2833cea',
    messagingSenderId: '364633043807',
    projectId: 'apiflet',
    databaseURL: 'https://apiflet-default-rtdb.firebaseio.com',
    storageBucket: 'apiflet.appspot.com',
    androidClientId: '364633043807-ao1j569621givu5mfksj843v9c4udjot.apps.googleusercontent.com',
    iosClientId: '364633043807-rvippnqstbno5m19odgtjlui0chtnn04.apps.googleusercontent.com',
    iosBundleId: 'com.example.driversapp2.RunnerTests',
  );
}
